import { createContext } from "react";

const Context = createContext(
    {
        //App states ----------------------------
        loggedIn: false,
        setLoggedIn: () => {},
        firstLogin: false,
        setFirstLogin: () => {},

        //NotLogged Layout ----------------------------
        //app login
        handleLogin: () => {},
        //login
        inEmail: "",
        setInEmail: () => {},
        inEmailError: "",
        setInEmailError: () => {},
        inPassword: "",
        setInPassword: () => {},
        inPasswordError: "",
        setInPasswordError: () => {},
        rememberMe: false,
        setRememberMe: () => {},
        loginError: "",
        setLoginError: () => {},
        //app register
        handleRegister: () => {},
        //register
        upName: "",
        setUpName: () => {},
        upNameError: "",
        setUpNameError: () => {},
        upLastName: "",
        setUpLastName: () => {},
        upLastNameError: "",
        setUpLastNameError: () => {},
        upEmail: "",
        setUpEmail: () => {},
        upEmailError: "",
        setUpEmailError: () => {},
        upPassword: "",
        setUpPassword: () => {},
        upPasswordError: "",
        setUpPasswordError: () => {},
        upCPassword: "",
        setUpCPassword: () => {},
        upConfirmPasswordError: "",
        setUpConfirmPasswordError: () => {},
        registerError: "",
        setRegisterError: () => {},
        registerSuccess: false,
        setRegisterSuccess: () => {},
        //app recovery
        handleRecovery: () => {},
        //recovery
        inRecoveryEmail: "",
        setInRecoveryEmail: () => {},
        inRecoveryEmailError: "",
        setInRecoveryEmailError: () => {},
        inRecoveryEmailSuccess: false,
        setInRecoveryEmailSuccess: () => {},

        //FirstLogin Layout ----------------------------
        //personal
        upCode: "",
        setUpCode: () => {},
        upCodeError: "",
        setUpCodeError: () => {},
        upPhoneNumber: "",
        setUpPhoneNumber: () => {},
        upPhoneNumberError: "",
        setUpPhoneNumberError: () => {},
        upDOB: "",
        setUpDOB: () => {},
        upDOBError: "",
        setUpDOBError: () => {},
        upCountry: "",
        setUpCountry: () => {},
        upCountryError: "",
        setUpCountryError: () => {},
        upCity: "",
        setUpCity: () => {},
        upCityError: "",
        setUpCityError: () => {},
        personalDone: false,
        setPersonalDone: () => {},
        //education
        upDegree: "",
        setUpDegree: () => {},
        upDegreeError: "",
        setUpDegreeError: () => {},
        upUniversity: "",
        setUpUniversity: () => {},
        upUniversityError: "",
        setUpUniversityError: () => {},
        upGraduationDate: "",
        setUpGraduationDate: () => {},
        upGraduationDateError: "",
        setUpGraduationDateError: () => {},
        //experience
        upJobTitle: "",
        setUpJobTitle: () => {},
        upJobTitleError: "",
        setUpJobTitleError: () => {},
        upCompany: "",
        setUpCompany: () => {},
        upCompanyError: "",
        setUpCompanyError: () => {},
        upMinSalary: "",
        setUpMinSalary: () => {},
        upMinSalaryError: "",
        setUpMinSalaryError: () => {},
        upMaxSalary: "",
        setUpMaxSalary: () => {},
        upMaxSalaryError: "",
        setUpMaxSalaryError: () => {}, 
        experienceDone: false,
        setExperienceDone: () => {},
        //skills
        hardSkills: [],
        setHardSkills: () => {},
        hardSkillsError: "",
        setHardSkillsError: () => {},
        softSkills: [],
        setSoftSkills: () => {},
        softSkillsError: "",
        setSoftSkillsError: () => {},
        skillsDone: false,
        setSkillsDone: () => {},
        //avatar
        avatar: null,
        setAvatar: () => {},
        avatarDone: false,
        setAvatarDone: () => {},
        //resume
        resume: null,
        setResume: () => {},
        resumeError: "",
        setResumeError: () => {},
        resumeDone: false,
        setResumeDone: () => {},
    }
);

export default Context;